### ISSUE TITLE
No module named gpu_sentry.client

### ISSUE THREAD

**Issue by tastyminerals** [jacenkow/gpu-sentry#1]
I have installed the dependencies and still getting the following error:
```
python3 gpu_sentry/cli.py -m client
Traceback (most recent call last):
  File "gpu_sentry/cli.py", line 29, in <module>
    from gpu_sentry.client import run_client
ModuleNotFoundError: No module named 'gpu_sentry'
```

**Comment by jacenkow** [comment]
Hi,
I was able to reproduce the error. Thanks for opening the issue.

Can you run `pip install -e .` in the root directory of this repository to link the package with your `python3` modules?
