### ISSUE TITLE
Gpu-box not shown on webpage

### ISSUE THREAD

**Issue by salil1809** [jacenkow/gpu-sentry#2]
Hey i followed your steps to install this on my computers
I started the client on one computer with gpu and started server with another computer. 
I edited the config.py in client: added client computer details in permit_clients and changed server hostname to the ip of the server computer but client box is not seen on the webpage hosted on server computer.
Please help

**Comment by jacenkow** [comment]
Hi,

Can you run following script on your GPU machine,

```
import socket
print(socket.gethostname())
```

and check if the key in `PERMIT_CLIENTS` is set to the exactly same value?

**Comment by salil1809** [comment]
![image](https://user-images.githubusercontent.com/42609569/52272701-95a05e80-296d-11e9-81d1-2514e23a435d.png)
![image](https://user-images.githubusercontent.com/42609569/52272739-ad77e280-296d-11e9-942d-9e8a036b8e39.png)
Please check what i am doing wrong

**Comment by jacenkow** [comment]
Could you change `SERVER_HOSTNAME = "http://192.168.25.207:8000/api"`?
I assume you don't use SSL?

**Comment by salil1809** [comment]
still not showing
do i have to edit something in server computer also?

**Comment by jacenkow** [comment]
Do you get any errors on your GPU machine, e.g. `requests.exceptions.ConnectionError`?

**Comment by salil1809** [comment]
when I start running the python file on the client
![image](https://user-images.githubusercontent.com/42609569/52397783-c4891280-2adc-11e9-86bf-716c64d393ef.png)
nothing prints, it justs goes to the next line

also, I can't access the page hosted on the server computer remotely
it only works on 127.0.0.1:8000 not the IP address of the computer

**Comment by salil1809** [comment]
![image](https://user-images.githubusercontent.com/42609569/52400915-7b3dc080-2ae6-11e9-82ed-e3599d500a79.png)
yeah after some time when i try to exit this command this error comes

**Comment by jacenkow** [comment]
Hi @salil1809 

Could you amend `gpu-sentry/server.py` file on your central server with

```
def run_server():
    """Run server to render incoming statistics."""
    app.run(
            debug=config.SERVER_DEBUG,
            host="0.0.0.0",  # Make the server visible on the network.
            port=config.SERVER_PORT)
```

**Comment by jacenkow** [comment]
Is your problem solved?

**Comment by jacenkow** [comment]
Please reopen if you still have problems.
