### ISSUE TITLE
Missing hostname

### ISSUE THREAD

**Issue by colinlaney** [jacenkow/gpu-sentry#4]
What if my server can't resolve hostnames of GPU-hosts? How to configure client- and server-side `config.py` one having IPs only?

**Comment by jacenkow** [comment]
Hi @colinlaney,

Can you change `gpu_sentry/client.py` line 78 (on your GPU machines) from

```
host = socket.gethostname()
```

to

```
host = socket.gethostbyname(socket.gethostname())
```

and then set the `PERMIT_CLIENTS` keys in `config.py` on your central server to the corresponding values as you get using the following script (on your GPU machines)

```
import socket
print(socket.gethostbyname(socket.gethostname()))
```

**Comment by jacenkow** [comment]
Please reopen if you still have problems.
